# .streamlit/secrets.toml

[connections.snowflake]
account = "LDDPNIK.NF82582.snowflakecomputing.com"
user = "AilbheTraining"
password = "Riccione04/23"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
